name: "Publish Package"
on:
  push:
    branches:
      - main
     paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  publish:
    runs-on: ubuntu-latest
     env:
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE, so workflow can access it.
      - uses: actions/checkout@v2

      - name: Install dependecies
      - run: npm ci

      - name: Run linter
      - run: npm run lint

      - name: Run prettier
      - run: npm run prettier

      - name: Run build
      - run: npm run build

       # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@markoarthofer22'
      
        - name: Bump version and push tag
        uses: TriPSs/conventional-changelog-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          preset: 'react'
          tag-prefix: ''
          output-file: 'CHANGELOG.md'

      - name: Publish package
        run: "npm publish "
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}