import './scss/Defaults.scss';
import './scss/App.scss';

export { default as Button } from './components/buttons/button.component';
export { default as Dropdown } from './components/dropdown/dropdown.component';
export { default as InputComponent } from './components/input/input.component';
export { default as InputTypePhone } from './components/input/input-type-phone.component';
export { default as GlobalLoader } from './components/loaders/global.loader.component';
export { default as Popup } from './components/popup/popup.component';
export { default as Select } from './components/select/select.component';
export { default as Tooltip } from './components/badge/badge.component';
export { default as Dialog } from './models/dialog/dialog.component';
export { default as HeroBox } from './models/hero-box/hero-box.component';
export { default as NotificationBox } from './models/notification-box/notification-box.component';
export { default as CustomSwiper } from './models/swiper/swiper.component';
export { default as Breadcrumbs } from './components/breadcrumbs/breadcrumbs.component';
export { default as Hamburger } from './components/hamburger-menu/hamburger.component';
export { default as QuantityInput } from './components/quantity-input/quantity-input.component';
export { default as JumpToTop } from './components/jump-to-top/jump-to-top.component';
export { default as Badge } from './components/badge/badge.component';
export { default as GoogleAnalytics } from './components/google-analytics/google-analytics.component';
export { default as SliderBar } from './components/slider-bar/slider-bar.components';
export { default as SocialCards } from './models/social-network-cards/social-network-cards.component';
export { default as SwitchButton } from './components/switch-button/switch-button.component';
