name: 'Publish Package'
on:
    workflow_run:
        workflows: ['Publish Packages Lerna']
        branches: [main]
        types:
            - completed
        paths-ignore:
            - 'package.json'
            - 'CHANGELOG.md'

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Check-out repository under $GITHUB_WORKSPACE, so workflow can access it.
              uses: actions/checkout@v2

            - name: Install dependecies
              run: npm run prepare:local
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Run build
              run: npm run build:bundle

              # Setup .npmrc file to publish to GitHub Packages
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org/'
                  scope: '@markoarthofer22'

            - name: Publish package
              run: 'npm publish --access public'
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_KEY }}
