name: 'Publish Packages Lerna'
on:
    workflow_run:
        workflows: ['Publish tags']
        branches: [main]
        types:
            - completed
        paths-ignore:
            - 'package.json'
            - 'CHANGELOG.md'

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Check-out repository under $GITHUB_WORKSPACE, so workflow can access it.
              uses: actions/checkout@v2

            - name: Install dependecies
              run: |
                  rm -rf node_modules/
                  npm cache clear --force && npm ci
                  npx lerna bootstrap --no-ci
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Run build
              run: npm run build

              # Setup .npmrc file to publish to GitHub Packages
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org/'
                  scope: '@markoarthofer22'

            - name: Lerna publish
              run: npx lerna publish from-package --yes --registry="https://registry.npmjs.org/"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_KEY }}
